version: '3.8'

services:
  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # Kibana for Elasticsearch visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  # SpiderFoot
  spiderfoot:
    image: spiderfoot/spiderfoot:latest
    ports:
      - "5001:5001"
    volumes:
      - spiderfoot_data:/home/spiderfoot/data

  # OSINT Framework API
  osint_api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
      - elasticsearch
      - spiderfoot
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - SPIDERFOOT_HOST=http://spiderfoot:5001
      - SHODAN_API_KEY=${SHODAN_API_KEY}
    volumes:
      - ./:/app
      - ./config:/app/config

  # Nginx for serving dashboard
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - osint_api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./osint_dashboard.html:/usr/share/nginx/html/index.html

volumes:
  neo4j_data:
  neo4j_logs:
  elasticsearch_data:
  spiderfoot_data: